/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tempconverter;

import conversionStrategies.ConverterStrategy;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author ryancorbin
 */
public class TempConverterGui extends javax.swing.JFrame {
    
    protected TempConverterService servicer;

    /**
     * Creates new form TempConverterGui with a TempConverterService.
     */
    
    public TempConverterGui() {
        servicer = new TempConverterService();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromTextField = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        convertResultLabel = new javax.swing.JLabel();
        scalePicker = new JComboBox(servicer.getDegreeScales());
        convertToLabel = new javax.swing.JLabel();
        quitButton = new javax.swing.JButton();
        convertButton = new javax.swing.JButton();
        convertFromLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fromTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        fromTextField.setText("0");
        fromTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromTextFieldActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Temperature Converter");

        convertResultLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        convertResultLabel.setText("0 Degrees");

        scalePicker.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        scalePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scalePickerActionPerformed(evt);
            }
        });

        convertToLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        convertToLabel.setText("Farenheit");

        quitButton.setText("Quit");
        quitButton.setToolTipText("");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        convertFromLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        convertFromLabel.setText("Celsius");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convertToLabel)
                            .addComponent(convertFromLabel)
                            .addComponent(quitButton))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convertButton)
                            .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(convertResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(scalePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(title)
                .addGap(17, 17, 17)
                .addComponent(scalePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertFromLabel))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertResultLabel)
                    .addComponent(convertToLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quitButton)
                    .addComponent(convertButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   /**
    * On the selection of a conversion strategy it puts new text in the labels.
    * @param evt 
    */ 
    
    private void scalePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scalePickerActionPerformed
        ConverterStrategy current = (ConverterStrategy)scalePicker.getSelectedItem();
        convertFromLabel.setText(current.starter());
        convertToLabel.setText(current.oppisite());
        fromTextFieldActionPerformed(evt);
    }//GEN-LAST:event_scalePickerActionPerformed

    /**
     * After entering a number in the text box and pressing enter this function should
     * activate the convert button.
     * @param evt 
     */
    
    
    private void fromTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromTextFieldActionPerformed
        convertButtonActionPerformed(evt);
    }//GEN-LAST:event_fromTextFieldActionPerformed

    /**
     * Quits the program when activated.
     * @param evt 
     */
    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        quitProgram(evt);
    }//GEN-LAST:event_quitButtonActionPerformed

    /**
     * Pulls the textField input and ConverterStrategy and performs the calculation
     * with those.
     * @param evt 
     */
    
    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        try{
           Double incomingDegrees = Double.parseDouble(fromTextField.getText());
           ConverterStrategy current = (ConverterStrategy)scalePicker.getSelectedItem();
           Double outGoingDegrees = current.getConverted(incomingDegrees);
           String result = String.format("%.2f", outGoingDegrees);
           convertResultLabel.setText(result + " Degrees");   
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Invalid Entry. Please Enter a Number.");
        }
    }//GEN-LAST:event_convertButtonActionPerformed

    /**
     * The method that is called from the button method.  Quits the program.
     * @param evt 
     */
    
    private void quitProgram(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempConverterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempConverterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempConverterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempConverterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempConverterGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertButton;
    private javax.swing.JLabel convertFromLabel;
    private javax.swing.JLabel convertResultLabel;
    private javax.swing.JLabel convertToLabel;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JButton quitButton;
    private javax.swing.JComboBox scalePicker;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
